/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package kafka.sandbox.avro;
@org.apache.avro.specific.AvroGenerated
public enum MetricType implements org.apache.avro.generic.GenericEnumSymbol<MetricType> {
  TIMER, COUNTER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MetricType\",\"namespace\":\"kafka.sandbox.avro\",\"symbols\":[\"TIMER\",\"COUNTER\"],\"default\":\"TIMER\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
